/**
 * Issue #30: bundle the store-guard hook (src/hooks/store-guard.ts + its
 * mcp-approvals / tool-aliases / dialects imports) into ONE self-contained
 * CommonJS file and emit it as the committed module
 * src/generated/store-guard-bundle.ts → `{ source, sha256 }`.
 *
 * Committed rather than left in dist/ so a consumer that bundles
 * @gryphon/protect from source gets it with no extra build step. The A15
 * drift test re-bundles and fails when the committed module is stale:
 *
 *   npm run gen:store-guard -w @gryphon/protect
 */

const esbuild = require("esbuild");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const PKG = path.resolve(__dirname, "..");
const ENTRY = "src/hooks/store-guard.ts";
const OUT = path.join(PKG, "src", "generated", "store-guard-bundle.ts");

/** The bundled hook source. Deterministic for a given esbuild version. */
function bundleStoreGuard(): string {
  const r = esbuild.buildSync({
    absWorkingDir: PKG,
    entryPoints: [ENTRY],
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node18",
    write: false,
    legalComments: "none",
    charset: "utf8",
    logLevel: "silent",
  });
  return r.outputFiles[0].text;
}

function renderModule(source: string): string {
  const sha256 = crypto.createHash("sha256").update(source).digest("hex");
  return [
    "// GENERATED by packages/protect/scripts/build-store-guard.ts — do not edit.",
    "// The store-guard hook (issue #30), bundled into one self-contained file.",
    "// Regenerate: npm run gen:store-guard -w @gryphon/protect (a test fails on drift).",
    "",
    `const source: string = ${JSON.stringify(source)};`,
    `const sha256 = "${sha256}";`,
    "",
    "module.exports = { source, sha256 };",
    "",
  ].join("\n");
}

if (require.main === module) {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, renderModule(bundleStoreGuard()));
  console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
}

module.exports = { bundleStoreGuard, renderModule };
